### ISSUE TITLE
N00b question: how do I update a value?

### ISSUE THREAD

**Issue by cekvenich2** [DoctorEvidence/lmdb-js#103]
I want no dupe keys.

I want to update the value for a key. Do I have to remove the key first?

**Comment by kriszyp** [comment]
No, you do not have to remove the key first. By default, there are no duplicate keys, so just do a `db.put(key, value)` and it will update/replace the value for that key (as long as you are not using `dupSort: true`, which is what would enable duplicate keys).

**Comment by cekvenich2** [comment]
Perfect. THX!
