### ISSUE TITLE
can't be compiled - pkg fails

### ISSUE THREAD

**Issue by cekvenich2** [DoctorEvidence/lmdb-js#118]
re - https://github.com/vercel/pkg/issues/1444

I need to compile the app so no source code for my needs.
Love lmdb, but I need a key-value that can be compiled, eg pkg.

help please.

Cheers, Vic

**Comment by cekvenich2** [comment]
adding 	"main": "./dist/index.cjs",
to your package get it going, but then it can't see these 3 files:
> Warning Failed to make bytecode node16-x64 for file /snapshot/pkg/node_modules/ordered-binary/index.js
> Warning Failed to make bytecode node16-x64 for file /snapshot/pkg/node_modules/weak-lru-cache/index.js
> Warning Failed to make bytecode node16-x64 for file /snapshot/pkg/node_modules/weak-lru-cache/LRFUExpirer.js

**Comment by kriszyp** [comment]
I think lmdb-store, as well as the dependencies, need the "main" property in package.json. The "main" property is a very ancient artifact of old node package.json, and has long since been replaced by "exports", so I am surprised vercel/pkg is using it, but I can go ahead and add it to all the necessary packages.

**Comment by cekvenich2** [comment]
@kriszyp I'd really appreciate it. There are several other 'compilers', eg nexe, but I need one of them work.

**Comment by cekvenich2** [comment]
@kriszyp Ah... nexe works, does same thing as pkg
So I don't need that fix :-}. Pardon. I did not think of trying the other one. I did try a few other ones.
Consider un-doing that commit, since nexe can compile this module. Cheers.

**Comment by cekvenich2** [comment]
Actually - if you do release a version that works pkg: it would not be a bad thing.

**Comment by kriszyp** [comment]
The latest release should have the main entries (including a dependency packages)

**Comment by cekvenich2** [comment]
Thank you for support.
