### ISSUE TITLE
Can i search a value in subdb by searching it from main db

### ISSUE THREAD

**Issue by KaffinPX** [DoctorEvidence/lmdb-js#126]
![image](https://user-images.githubusercontent.com/73744616/149200813-49de1fe0-02a2-4782-82e1-ac691ffeb907.png)
This doesnt work

**Comment by kriszyp** [comment]
Sorry, no, you can't do that. Each database is a separate key-value store/btree. If you want some type of hierarchy, where can get multiple, best to do that with prefixes and suffixes to your keys (like you could put 'hello-1', 'hello-2' and then do a range query to get all the keys starting with 'hello-').

**Comment by KaffinPX** [comment]
Thanks
