### ISSUE TITLE
If you enable sharedStructuresKey, the structure shows up as the first entry in getRange

### ISSUE THREAD

**Issue by kylebernhardy** [DoctorEvidence/lmdb-js#128]
This started happening after v1.5.5

Sample code found here and was run against lmdb-js v2.1.5:

```
'use strict';

const lmdb = require('lmdb');

let env_init = {
    "path": './data',
    "mapSize": 1024 * 1024 * 1024,
    "maxReaders": 1000,
    "maxDbs":10000,
    sharedStructuresKey: Symbol.for('structures')
};

let env = lmdb.open(env_init);
let dbi = env.openDB('id', {
    create: true,
    dupSort: false,
    useVersions: true,
    sharedStructuresKey: Symbol.for('structures')
});

dbi.putSync(1, {id:1, name:"Kato"});


for (let { key, value} of dbi.getRange({})) {
    console.log(key, value);
}
```

Resulting output: 

```
Symbol(structures) [ [ 'id', 'name' ] ]

1 { id: 1, name: 'Kato' }
```

**Comment by kriszyp** [comment]
I think I would argue that the V2 behavior is actually a little more correct; it is iterating over _all_ the entries (and V1 -> V2 was a good time to make that change). To achieve the prior behavior of iterating through all entries with a key greater than symbols, you should be able to use `getRange({start: false})` (symbols < booleans < numbers < strings).

**Comment by kylebernhardy** [comment]
That makes a  lot of sense.  Thanks for the tip on an easy filter pattern!
