### ISSUE TITLE
Question about restoring an mdb file

### ISSUE THREAD

**Issue by kylebernhardy** [DoctorEvidence/lmdb-js#132]
Out of curiosity I was investigating using noSync: true and then causing a server outage while writes were occurring, which intentionally corrupts the mdb file.  Is there a way to restore a corrupted mdb file?

**Comment by kriszyp** [comment]
No, LMDB doesn't have any restore/fixing-of-corruption functionality that I am aware, and that's kind of why you want to avoid corruption :).

FWIW, in the past I have been to successfully replicate corruption with `noSync: true` using a VM, specifically Hyper-V on my windows box, and shutting down the VM, without actually have to physically turn off a computer. I haven't tried recently though.

**Comment by kylebernhardy** [comment]
:) good to know!  I did the same on my end with killing a Hyper-V VM.  The good news is I have also done the same with `overlappingSync: true` and the mdb is always stable.

**Comment by kriszyp** [comment]
Actually, I should mention that the newer LMDB version that we use does have a `MDB_PREVSNAPSHOT` flag, that allows you to revert to the previous snapshot, in the case that the newest db version/snapshot is corrupted, but the previous one is ok (but I think with `noSync: true` there is pretty decent likelihood that if the latest version is corrupt, the previous one will be too). This flag is actually used by overlappingSync internally to revert back to the "durable" snapshot.

`MDB_PREVSNAPSHOT` flag is available in lmdb-js with the `usePreviousSnapshot` flag. If you have corrupted a db in your testing, might be interesting to try the flag to see if the previous snapshot is valid or corrupted as well.

**Comment by kylebernhardy** [comment]
I'm always impressed with how much work you have put into lmdb-js. 
Yeah it would be a good assumption the snapshots would all be in a bad state, however I'll check it out & let you know what i find!

**Comment by kylebernhardy** [comment]
Seems like the `noSync: true` & `usePreviousSnapshot: true` don't play well together.  Written data doesn't seem to be found, at least in our implementation. Not worth tracking down, but wanted to share with you.

**Comment by kriszyp** [comment]
> The good news is I have also done the same with overlappingSync: true and the mdb is always stable.

Thanks for testing this, I know these types of tests are onerous and time-consuming (which is why I haven't done any recently), so great to hear overlapping sync is working as hoped! With this data point, I am tempted to turn overlapping sync on by default (for non-windows OS) in a future lmdb-js version.
