### ISSUE TITLE
docker build is failing at run npm install command - Build is failing since release of lmdb 2.2.2

### ISSUE THREAD

**Issue by santoshtechedge** [DoctorEvidence/lmdb-js#141]
> lmdb@2.2.1 install /app/node_modules/gatsby/node_modules/lmdb
> node-gyp-build

make: Entering directory '/app/node_modules/gatsby/node_modules/lmdb/build'
  CXX(target) Release/obj.target/lmdb/src/lmdb-js.o
  CC(target) Release/obj.target/lmdb/dependencies/lmdb/libraries/liblmdb/midl.o
  CC(target) Release/obj.target/lmdb/dependencies/lmdb/libraries/liblmdb/chacha8.o
  CC(target) Release/obj.target/lmdb/dependencies/lz4/lib/lz4.o
  CXX(target) Release/obj.target/lmdb/src/writer.o
  CXX(target) Release/obj.target/lmdb/src/env.o
  CXX(target) Release/obj.target/lmdb/src/compression.o
  CXX(target) Release/obj.target/lmdb/src/ordered-binary.o
  CXX(target) Release/obj.target/lmdb/src/misc.o
../src/misc.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE clearKeptObjects(Nan::NAN_METHOD_ARGS_TYPE)':
../src/misc.cpp:207:28: error: 'class v8::Isolate' has no member named 'ClearKeptObjects'
  207 |     Isolate::GetCurrent()->ClearKeptObjects();
      |                            ^~~~~~~~~~~~~~~~
make: *** [lmdb.target.mk:145: Release/obj.target/lmdb/src/misc.o] Error 1
make: Leaving directory '/app/node_modules/gatsby/node_modules/lmdb/build'
gyp ERR! build error

**Comment by kriszyp** [comment]
Should be fixed/published in v2.2.3.
