### ISSUE TITLE
how to clear a db?

### ISSUE THREAD

**Issue by timotejroiko** [DoctorEvidence/lmdb-js#150]
Hello, im using lmdb as multi-process cache layer on top of several data files, and sometimes i need to update one of those data files and invalidate the entire cache responsible for that file (either in a sub-db or in a separate lmdb file), what is the best way to do this from an external process, without interrupting the long running processes that are using it?

These files can be quite large, with tens of thousands of entries so i was hoping there is a more efficient way than looping over all keys and deleting them one by one.

**Comment by kriszyp** [comment]
Is `db.clearAsync` (or `clearSync`) what you are looking for? (I guess it is in the typings but not the README/docs https://github.com/DoctorEvidence/lmdb-js/blob/master/index.d.ts#L233 . I should probably add it to the actual docs though).

**Comment by timotejroiko** [comment]
ahh i only looked in the readme haha, thanks! It would be nice to have in the readme as well yes, or on a separate MD file listing all props and methods :)
