### ISSUE TITLE
getRange only returns 59 items.

### ISSUE THREAD

**Issue by KaffinPX** [DoctorEvidence/lmdb-js#154]
```js
const bridgings = db.openDB('bridge').getRange({ start: "1", end: db.openDB('bridge').getStats().entryCount.toString(), limit: db.openDB('bridge').getStats().entryCount.toString() })
```

**Comment by kriszyp** [comment]
It is not clear what you are asking about here, how many items are in your database, or why `getRange` should return something other 59 items. However, a couple notes

- You are converting numbers to strings for keys, and strings have a different order (lexical) than numbers in a database. That is "1" < "10" < "2", so if you are using strings to store numbers, getRange might not behave the way you expect.
- The `end` parameter is exclusive, so the key provided for `end` will _not_ be included in the getRange results.
- It is best to only open a database once, opening the same database multiple times needlessly creates extra objects.

**Comment by KaffinPX** [comment]
Ty, also it was for testing :)
