### ISSUE TITLE
Deno module runs non deno compatible code.

### ISSUE THREAD

**Issue by boehs** [DoctorEvidence/lmdb-js#163]
```
➜  ltcarchive deno run -A --unstable dbtest.ts
Download https://deno.land/x/lmdb@v2.3.6/native.js
error: Relative import path "module" not prefixed with / or ./ or ../
    at https://deno.land/x/lmdb@v2.3.6/native.js:3:31
```

For your convenience, the line in question is

```js
import { createRequire } from 'module';
```

This code works in node, but not in deno (`module` is not a thing). The deno std provides a polyfill, but it's unclear how to do it the proper way on both platforms

https://deno.land/std/node

**Comment by kriszyp** [comment]
lmdb v2.3+ requires Deno 1.23+ (predicted version with NAPI support, but which obviously doesn't exist yet). For earlier versions of Deno, you need to use lmdb v2.2.x (this is in the docs, btw).

**Comment by boehs** [comment]
I misread the docs. Sorry!

**Comment by kriszyp** [comment]
BTW, if you want to follow it, here is the primary PR that I am waiting on: https://github.com/denoland/deno/pull/13633
