### ISSUE TITLE
published index.d.ts is somehow outdated with master branch

### ISSUE THREAD

**Issue by gogoout** [DoctorEvidence/lmdb-js#96]
https://cdn.jsdelivr.net/npm/lmdb@latest/index.d.ts
https://cdn.jsdelivr.net/npm/lmdb-store@latest/index.d.ts
For example, there should be a `transactionAsync` function for Database there but isn't. However, seems the type exists for `lmdb-store` package.

**Comment by kriszyp** [comment]
v2.0 is going out on `lmdb`, so https://cdn.jsdelivr.net/npm/lmdb@latest is the latest v2.0 beta release, in which I intended to deprecate `transactionAsync` in favor of just `transaction`. I guess should actually still include that in the typings though. https://cdn.jsdelivr.net/npm/lmdb-store@latest has v1.x.

**Comment by kriszyp** [comment]
Updating the typings on `v2.0` branch. Will merge `v2.0` into `master` very soon.

**Comment by kriszyp** [comment]
V2.0 is now merged into master and published.
