### ISSUE TITLE
lmdb doesn't work if installed with --ignore-optional

### ISSUE THREAD

**Issue by KyleAMathews** [DoctorEvidence/lmdb-js#97]
As lmdb uses `msgpackr` by default so a few Gatsby users have had problems e.g. see https://github.com/gatsbyjs/gatsby/discussions/33927

So the solution I think is to either try/catch requiring msgpackr or to mark it as a required dependency.

**Comment by kriszyp** [comment]
Would it be feasible to include msgpackr as required dependency of gatsby, if you are using the default msgpackr encoding in lmdb?

For try/catch, I could do that, but would have to _some_ fallback, which I suppose would probably be JSON. However, it might be considered a bit of a hazard that your database could end up in a completely different format based on your npm setting options (and switching them would render you db unreadable).

That being said, making msgpackr a required dependency seems quite reasonable, it is very a light dependency as far as node deps go. I think I will go ahead and do that.

**Comment by kriszyp** [comment]
I published v1.6.14 with this update to make msgpackr a required dependency.

**Comment by KyleAMathews** [comment]
Thanks!
