### ISSUE TITLE
v2.0.0 console.log at startup in node-index.js 

### ISSUE THREAD

**Issue by sbittmann** [DoctorEvidence/lmdb-js#98]
Just a small visual "bug" in v2, maybe you got some time to remove this 😄:
![image](https://user-images.githubusercontent.com/26568773/142730521-6b538572-e9e4-4114-aea3-0a6a846f3d9f.png)

**Comment by kriszyp** [comment]
Oops! Thanks for reporting this, I will get it fixed!

**Comment by devongovett** [comment]
Could we get the fix published? Just updated Parcel to the latest version and we are seeing this log message. 😄

**Comment by kriszyp** [comment]
Published in v2.0.1.
